export const COLLECT_ACTION_REQUEST = 'PRO/COLLECT_ACTION_REQUEST';// 标识正在获取标签
export const COLLECT_ACTION_FAILURE = 'PRO/COLLECT_ACTION_FAILURE';//  获取失败
export const COLLECT_ACTION_SUCCESS = 'PRO/COLLECT_ACTION_SUCCESS';// 获取成功

export const COLLECT_ACTION_ADD = 'PRO/COLLECT_ACTION_ADD'; // 增加收藏
export const COLLECT_ACTION_DELETE = 'PRO/COLLECT_ACTION_DELETE'; // 删除收藏
export const COLLECT_ACTION_UPDATE = 'PRO/COLLECT_ACTION_UPDATE'; // 修改收藏
export const COLLECT_ACTION_GETCOLLECTSBYCONDITION = 'PRO/COLLECT_ACTION_GETCOLLECTSBYCONDITION'; // 根据条件获取收藏
export const COLLECT_ACTION_GETTITLEBYURL = 'PRO/COLLECT_ACTION_GETTITLEBYURL'; // 获取源url的标题
