export const USER_DETAILS_GET_REQUEST = 'PRO/USER_DETAILS_GET_REQUEST';// 标识正在获取用户
export const USER_DETAILS_GET_SUCCESS = 'PRO/USER_DETAILS_GET_SUCCESS';//  获取成功
export const USER_DETAILS_GET_FAILURE = 'PRO/USER_DETAILS_GET_FAILURE';// 获取失败
