export const ARTICLE_ACTION_REQUEST = 'PRO/ARTICLE_ACTION_REQUEST';// 标识正在获取
export const ARTICLE_ACTION_FAILURE = 'PRO/ARTICLE_ACTION_FAILURE';//  获取失败
export const ARTICLE_ACTION_SUCCESS = 'PRO/ARTICLE_ACTION_SUCCESS';// 获取成功

export const ARTICLE_ACTION_ADD = 'PRO/ARTICLE_ACTION_ADD';// 添加文章
export const ARTICLE_ACTION_DELETE = 'PRO/ARTICLE_ACTION_DELETE';// 删除文章
export const ARTICLE_ACTION_UPDATE = 'PRO/ARTICLE_ACTION_UPDATE';// 修改文章
export const ARTICLE_ACTION_GETARTICLEBYID = 'PRO/ARTICLE_ACTION_GETARTICLEBYID';// 根据id获取文章
export const ARTICLE_ACTION_GETARTICLESBYUSERID = 'PRO/ARTICLE_ACTION_GETARTICLESBYUSERID';// 根据用户id,标题获取文章
