export const TAGS_ACTION_REQUEST = 'PRO/TAGS_ACTION_REQUEST';// 标识正在获取标签
export const TAGS_ACTION_FAILURE = 'PRO/TAGS_ACTION_FAILURE';//  获取失败
export const TAGS_ACTION_SUCCESS = 'PRO/TAGS_ACTION_SUCCESS';// 获取成功
export const TAGS_ACTION_RESULT_RESET = 'PRO/TAGS_ACTION_RESULT_RESET';// 标签结果数据重置：解决搜索时有旧数据问题

export const TAGS_ACTION_ADD = 'PRO/TAGS_ACTION_ADD';// 添加标签
export const TAGS_ACTION_DELETE = 'PRO/TAGS_ACTION_DELETE';// 删除标签
export const TAGS_ACTION_UPDATE = 'PRO/TAGS_ACTION_UPDATE';// 修改标签
export const TAGS_ACTION_GETTAGBYID = 'PRO/TAGS_ACTION_GETTAGBYID';// 通过id获取标签
export const TAGS_ACTION_GETTAGSBYUSERID = 'PRO/TAGS_ACTION_GETTAGSBYUSERID';// 通过用户id获取标签---滚动加载版
export const TAGS_ACTION_GETTAGSBYUSERID_PAGING = 'PRO/TAGS_ACTION_GETTAGSBYUSERID_PAGING';// 通过用户id获取标签---分页版
export const TAGS_ACTION_ADD_CHECKED = 'PRO/TAGS_ACTION_ADD_CHECKED';// 通过用户id获取标签---分页版
