export const ARTICLE_ACTION_REQUEST = 'PRO/ARTICLE_ACTION_REQUEST';// 标识正在获取
export const ARTICLE_ACTION_FAILURE = 'PRO/ARTICLE_ACTION_FAILURE';//  获取失败
export const ARTICLE_ACTION_SUCCESS = 'PRO/ARTICLE_ACTION_SUCCESS';// 获取成功

